### ISSUE TITLE
Suggestion: get_wordpress_paths.py should download files into its own directory

### ISSUE THREAD

**Issue by johnsaigle** [p0dalirius/webapp-wordlists#1]
Hello, thanks for making this tool!

I ran the script `get_wordpress_paths.py` from a different directory on my system. The script ended up downloading files to that directory, not into the folder where the python script is located.

You can use something like this to make the script download to its directory:

```python
destination = os.path.dirname(__file__)
```

**Comment by p0dalirius** [comment]
Hello,

Thanks for this issue, I'm adding this to all the scripts :+1: 

Best regards
